[package]
name = "pgwire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = "0.1.2"
tokio-util = { version = "0.7.3", features = ["codec", "io"] }
derive-new = "0.5"
bytes = "1.1.0"
time = "0.3"
futures = "0.3"
async-trait = "0.1"
rand = "0.8"
tokio = { version = "1.19", features = ["net"] }

[dev-dependencies]
tokio = { version = "1.19", features = ["rt-multi-thread", "net", "io-util", "macros"]}
