[package]
name = "pgwire"
version = "0.3.0"
edition = "2021"
authors = ["Ning Sun <sunng@pm.me>"]
license = "MIT"
description = "Postgresql wire protocol implemented as a library"
keywords = ["database", "postgresql"]
categories = ["database"]
homepage = "https://github.com/sunng87/pgwire"
repository = "https://github.com/sunng87/pgwire"
documentation = "https://docs.rs/crate/pgwire/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
getset = "0.1.2"
derive-new = "0.5"
bytes = "1.1.0"
time = "0.3"
futures = "0.3"
async-trait = "0.1"
rand = "0.8"
thiserror = "1"
postgres-types = "0.2"

tokio = { version = "1.19", features = ["net", "rt"], optional = true}
tokio-util = { version = "0.7.3", features = ["codec", "io"], optional = true }

[dev-dependencies]
tokio = { version = "1.19", features = ["rt-multi-thread", "net", "io-util", "macros"]}
rusqlite = { version = "0.28.0", features = ["bundled", "column_decltype"] }
hex = "0.4"

[features]
default = ["tokio_support"]
tokio_support = ["tokio", "tokio-util"]

[[example]]
name = "server"
required-features = ["tokio_support"]
