[package]
name = "pgwire"
version = "0.6.2"
edition = "2021"
authors = ["Ning Sun <sunng@pm.me>"]
license = "MIT/Apache-2.0"
description = "Postgresql wire protocol implemented as a library"
keywords = ["database", "postgresql"]
categories = ["database"]
homepage = "https://github.com/sunng87/pgwire"
repository = "https://github.com/sunng87/pgwire"
documentation = "https://docs.rs/crate/pgwire/"
readme = "README.md"

[dependencies]
log = "0.4"
getset = "0.1.2"
derive-new = "0.5"
bytes = "1.1.0"
time = "0.3"
futures = "0.3"
async-trait = "0.1"
rand = "0.8"
thiserror = "1"
postgres-types = "0.2"
md5 = "0.7"
## scram libraries
base64 = "0.20"
pbkdf2 = "0.11.0"
hmac = "0.12.1"
sha2 = "0.10.6"

tokio = { version = "1.19", features = ["net", "rt", "io-util", "time"], optional = true}
tokio-util = { version = "0.7.3", features = ["codec", "io"], optional = true }
tokio-rustls = { version = "0.23", optional = true }

[dev-dependencies]
hex = "0.4"
tokio = { version = "1.19", features = ["rt-multi-thread", "net", "macros"]}
rusqlite = { version = "0.28.0", features = ["bundled", "column_decltype"] }
## for loading custom cert files
rustls-pemfile = { version = "1.0" }
## webpki-roots has mozilla's set of roots
## rustls-native-certs loads roots from current system
gluesql = "0.13"

[features]
default = ["tokio_support"]
tokio_support = ["tokio", "tokio-util", "tokio-rustls"]

[[example]]
name = "server"
required-features = ["tokio_support"]
